### ISSUE TITLE
"Thriving Online Business" wrong code

### ISSUE THREAD

**Issue by Nord1cWarr1or** [glad-tidings/TapswapTasks#3]
![изображение](https://github.com/user-attachments/assets/5c30555e-842e-4e2a-982d-912f9e243e04)

**Comment by BraveCanister** [comment]
No worries, the whole script doesn't work.

**Comment by glad-tidings** [comment]
fix this

**Comment by Nord1cWarr1or** [comment]
> fix this

yep, but some codes are still wrong

**Comment by Nord1cWarr1or** [comment]
like "Create & Sell Online Courses for Profit"
"TapSwap & Binance’s Big Promo Step-by-Step Guide!"
code not appears
